# ak函数北上资金

In [23]:
# https://akshare.xyz/data/stock/stock.html#id122

import akshare as ak

stock_hsgt_hist_em_df = ak.stock_hsgt_hist_em(symbol="沪股通")
print(stock_hsgt_hist_em_df)

              日期   当日成交净买额     买入成交额     卖出成交额    历史累计净买额    当日资金流入      当日余额  \
0     2023-01-30   94.3504  395.4183  301.0679  9710.3453  105.1182  414.8818
1     2023-01-20   42.1054  244.8049  202.6995  9615.9949   50.5336  469.4664
2     2023-01-19   56.9071  232.0952  175.1881  9573.8895   67.1782  452.8218
3     2023-01-18   19.9025  187.5199  167.6174  9516.9824   29.4050  490.5950
4     2023-01-17   43.1586  227.2377  184.0791  9497.0799   53.2918  466.7082
...          ...       ...       ...       ...        ...       ...       ...
1894  2014-11-21   21.9953   24.3055    2.3102   236.4024   23.4100  106.5900
1895  2014-11-20   21.4194   23.0973    1.6779   214.4071   22.7600  107.2400
1896  2014-11-19   24.9677   26.6951    1.7274   192.9877   26.1200  103.8800
1897  2014-11-18   47.1967   49.4367    2.2400   168.0200   48.4500   81.5500
1898  2014-11-17  120.8233  120.8233    0.0000   120.8233  130.0000    0.0000

       领涨股  领涨股涨跌幅     上证指数    涨跌幅
0      李子园   10.02  3269.32  0.140
1     中航产融   10.02  3264.81  0.760
2     中望软件   11.16  3240.28  0.490
3      美凯龙   10.05  3224.41  0.005
4      美凯龙   10.10  3224.24 -0.100
...    ...     ...      ...    ...
1894  大众公用   10.02  2486.79  1.390
1895  厦门国贸    9.37  2452.66  0.070
1896  君正集团    6.85  2450.99 -0.220
1897  厦门国贸   10.06  2456.37 -0.710
1898   唐山港    9.98  2474.01 -0.190

[1899 rows x 11 columns]

In [24]:
df = stock_hsgt_hist_em_df
df

,日期,当日成交净买额,买入成交额,卖出成交额,历史累计净买额,当日资金流入,当日余额,领涨股,领涨股涨跌幅,上证指数,涨跌幅
0,2023-01-30,94.3504,395.4183,301.0679,9710.3453,105.1182,414.8818,李子园,10.02,3269.32,0.140
1,2023-01-20,42.1054,244.8049,202.6995,9615.9949,50.5336,469.4664,中航产融,10.02,3264.81,0.760
2,2023-01-19,56.9071,232.0952,175.1881,9573.8895,67.1782,452.8218,中望软件,11.16,3240.28,0.490
3,2023-01-18,19.9025,187.5199,167.6174,9516.9824,29.4050,490.5950,美凯龙,10.05,3224.41,0.005
4,2023-01-17,43.1586,227.2377,184.0791,9497.0799,53.2918,466.7082,美凯龙,10.10,3224.24,-0.100
...,...,...,...,...,...,...,...,...,...,...,...
1894,2014-11-21,21.9953,24.3055,2.3102,236.4024,23.4100,106.5900,大众公用,10.02,2486.79,1.390
1895,2014-11-20,21.4194,23.0973,1.6779,214.4071,22.7600,107.2400,厦门国贸,9.37,2452.66,0.070
1896,2014-11-19,24.9677,26.6951,1.7274,192.9877,26.1200,103.8800,君正集团,6.85,2450.99,-0.220
1897,2014-11-18,47.1967,49.4367,2.2400,168.0200,48.4500,81.5500,厦门国贸,10.06,2456.37,-0.710
1898,2014-11-17,120.8233,120.8233,0.0000,120.8233,130.0000,0.0000,唐山港,9.98,2474.01,-0.190

# tushare 北上资金
https://tushare.pro/document/2?doc_id=47

In [25]:
import yaml
import tushare as ts
import pandas as pd
conf = yaml.load(open('../../conf/config.yml', 'r', encoding='utf-8').read(), Loader=yaml.FullLoader)
print(conf['token'][:10])
pro = ts.pro_api(conf['token'])

bf542ab154

In [21]:
import pandas as pd
dfs = []
for year in range(2015,2024):
    start = f'{year}0101'
    end = f'{year}1231'
    print(start,'~',end)
    df = pro.moneyflow_hsgt(start_date=start, end_date=end)
    dfs.append(df)
df = pd.concat(dfs)
print(df)

bf542ab154
20150101 ~ 20151231
20160101 ~ 20161231
20170101 ~ 20171231
20180101 ~ 20181231
20190101 ~ 20191231
20200101 ~ 20201231
20210101 ~ 20211231
20220101 ~ 20221231
20230101 ~ 20231231
   trade_date   ggt_ss   ggt_sz      hgt      sgt  north_money  south_money
0    20151231   432.00     None  -454.00     None      -454.00       432.00
1    20151230   766.00     None   664.00     None       664.00       766.00
2    20151229   428.00     None   906.00     None       906.00       428.00
3    20151228   545.00     None    35.00     None        35.00       545.00
4    20151224   212.00     None      NaN     None         0.00       212.00
..        ...      ...      ...      ...      ...          ...          ...
10   20230109  -859.83  -365.28  4723.00   2977.3      7700.30     -1225.11
11   20230106  -987.00  -356.75  4471.66   1594.6      6066.26     -1343.75
12   20230105  1789.44   1508.9  5658.67  7094.66     12753.33      3298.34
13   20230104  2372.26  2637.53   338.41  1505.79      1844.20      5009.79
14   20230103  3121.04  1129.18 -2135.00   1490.0      -645.00      4250.22

[1902 rows x 7 columns]

In [33]:
import pandas as pd
dfs = []
for year in range(2015,2016):
    start = f'{year}0101'
    end = f'{year}1231'
    print(start,'~',end)
    df = pro.moneyflow_hsgt(start_date=start, end_date=end)
    dfs.append(df)
df = pd.concat(dfs)
print(df)

20150101 ~ 20151231
    trade_date  ggt_ss ggt_sz     hgt   sgt  north_money  south_money
0     20151231   432.0   None  -454.0  None       -454.0        432.0
1     20151230   766.0   None   664.0  None        664.0        766.0
2     20151229   428.0   None   906.0  None        906.0        428.0
3     20151228   545.0   None    35.0  None         35.0        545.0
4     20151224   212.0   None     NaN  None          0.0        212.0
..         ...     ...    ...     ...   ...          ...          ...
232   20150109   802.0   None  1617.0  None       1617.0        802.0
233   20150108   637.0   None  1078.0  None       1078.0        637.0
234   20150107   909.0   None  1753.0  None       1753.0        909.0
235   20150106   968.0   None  2091.0  None       2091.0        968.0
236   20150105  1730.0   None  4689.0  None       4689.0       1730.0

[237 rows x 7 columns]

# tushare北向资金的10大股
https://tushare.pro/document/2?doc_id=48

In [34]:
import pandas as pd
dfs = []
for year in range(2015,2017):
    start = f'{year}0101'
    end = f'{year}1231'
    print(start,'~',end)
    df = pro.hsgt_top10(start_date=start, end_date=end,market_type='1')
    dfs.append(df)
    df = pro.hsgt_top10(start_date=start, end_date=end,market_type='2')
    dfs.append(df)

df = pd.concat(dfs)
print(df)

20150101 ~ 20151231
20160101 ~ 20161231
    trade_date    ts_code  name   close  change rank market_type       amount  \
0     20151231  601933.SH  永辉超市   10.10 -2.2265    1           1  326354253.0
1     20151231  601318.SH  中国平安   36.00  0.6711    6           1   50307814.0
2     20151231  600887.SH  伊利股份   16.43 -0.6651    9           1   31914705.0
3     20151231  600881.SH  亚泰集团    7.24 -0.4127    4           1   54296935.0
4     20151231  600519.SH  贵州茅台  218.19 -0.3061    5           1   51744263.0
..         ...        ...   ...     ...     ...  ...         ...          ...
295   20161116  600585.SH  海螺水泥   18.05 -1.1501    5           1   76569452.0
296   20161116  600519.SH  贵州茅台  313.15 -0.2739    2           1  117810165.0
297   20161116  600487.SH  亨通光电   19.15  1.9159    3           1   88376172.0
298   20161116  600030.SH  中信证券   17.46  0.0573    6           1   75330725.0
299   20161116  600016.SH  民生银行    9.19 -0.2172    8           1   46428664.0

      net_amount         buy         sell
0   -298554305.0  13899974.0  312454279.0
1     16620610.0  33464212.0   16843602.0
2    -16788683.0   7563011.0   24351694.0
3    -53243831.0    526552.0   53770383.0
4     -6319041.0  22712611.0   29031652.0
..           ...         ...          ...
295   42238456.0  59403954.0   17165498.0
296  -50916725.0  33446720.0   84363445.0
297  -17804006.0  35286083.0   53090089.0
298   69442985.0  72386855.0    2943870.0
299   46428664.0  46428664.0          0.0

[600 rows x 11 columns]